site_name: ANNarchy

theme:
  name: material

  features:
     - toc.integrate
     - header.autohide
#    - navigation.tabs
#    - navigation.expand
#    - navigation.sections
  
  palette:
    primary: black
    accent: indigo

  icon:
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2021 Julien Vitay, Helge Ülo Dinkelbach, Fred H. Hamker
repo_url: https://github.com/vitay/ANNarchy_future


plugins:
  - search
  - mkdocstrings


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 'index.md'
  - 'Manual':
    - 'manual/structure.md'
    - 'manual/neuron.md'
  - 'Reference':
    - 'api/network.md'
    - 'api/neuron.md'
    - 'api/synapse.md'
    - 'api/equations.md'
    - 'api/population.md'
    - 'api/projection.md'
  - 'Contributing':
    - 'contributing/structure.md'
    - 'contributing/parser.md'
    - 'contributing/generator.md'
  - 'CHANGELOG.md'
  - 'License.md'