site_name: ANNarchy

theme:
  name: material

  features:
     - toc.integrate
#    - navigation.tabs
#    - navigation.expand
#    - navigation.sections
  
  palette:
    primary: black
    accent: indigo

plugins:
  - search
  - mkdocstrings


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 'index.md'
  - 'Manual':
    - 'manual/structure.md'
    - 'manual/neuron.md'
  - 'Reference':
    - 'api/network.md'
    - 'api/neuron.md'
    - 'api/population.md'
  - 'Contributing':
    - 'contributing/structure.md'
    - 'contributing/parser.md'